#!/bin/sh
set -e

MISSPELLED=$(cat docs/*.md | grep -v '!' | aspell --lang=en --encoding=utf-8 --personal=./.aspell.en.pws list | sort -u)
if [ "$MISSPELLED" != "" ]
then
    MISSPELLED="$MISSPELLED\n"
fi
NB_MISSPELLED=`echo -n "$MISSPELLED" | wc -l`

if [ "$NB_MISSPELLED" -gt 0 ]
then
    echo ">> Words that might be misspelled, please check:$NC"
    MISSPELLED=`echo "$MISSPELLED" | sed -E ':a;N;$!ba;s/\n/, /g'`
    echo "$MISSPELLED"
    COMMENT="$NB_MISSPELLED words might be misspelled, please check them: $MISSPELLED"
    exit 1
else
    COMMENT="No spelling errors, congratulations!"
    echo ">> $COMMENT $NC"
    exit 0
fi
