#!/usr/bin/env python
from setuptools import setup, find_packages
import shutil

with open("./docs/conf.orig.py", "r") as src:
    with open("./docs/conf.py", "w") as dst:
        dst.write("# FILE COPIED FROM conf.orig.py; DO NOT CHANGE\n")
        shutil.copyfileobj(src, dst)

setup(
    name="brianmay",
    use_scm_version={},
    setup_requires=['setuptools_scm'],
    url='https://github.com/brianmay/resume/',
    author='Brian May',
    author_email='brian@linuxpenguins.xyz',
    description='Brian May\'s Resume',
    packages=find_packages(),
    license="GPL2+",
    long_description=open('README.rst').read(),
    classifiers=[
        "Development Status :: 6 - Mature",
        "Environment :: Console",
        "Framework :: Django :: 1.9",
        "Framework :: Sphinx",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: "
            "GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: Android",
        "Operating System :: OS Independent",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Unix",
        "Programming Language :: Ada",
        "Programming Language :: C++",
        "Programming Language :: Java",
        "Programming Language :: JavaScript",
        "Programming Language :: Perl",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Unix Shell",
        "Topic :: Communications :: Chat",
        "Topic :: Communications :: Email",
        "Topic :: Communications :: Internet Phone",
        "Topic :: Communications :: Telephony",
        "Topic :: Database :: Database Engines/Servers",
        "Topic :: Documentation :: Sphinx",
        "Topic :: Internet :: Name Service (DNS)",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Multimedia :: Graphics :: 3D Modeling",
        "Topic :: Multimedia :: Graphics :: 3D Rendering",
        "Topic :: Multimedia :: Graphics :: Capture :: Digital Camera",
        "Topic :: Multimedia :: Video",
        "Topic :: Security :: Cryptography",
        "Topic :: Software Development :: Bug Tracking",
        "Topic :: Software Development :: Build Tools",
        "Topic :: Software Development :: Documentation",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Testing",
        "Topic :: Software Development :: Version Control",
        "Topic :: Terminals",
        "Topic :: System :: Networking",
        "Topic :: System :: Networking :: Firewalls",
        "Topic :: System :: Networking :: Monitoring",
        "Topic :: System :: Networking :: Time Synchronization",
        "Topic :: System :: Operating System Kernels :: Linux",
        "Topic :: System :: Shells",
        "Topic :: System :: Systems Administration "
        ":: Authentication/Directory :: LDAP",
        "Topic :: Text Editors :: Emacs",
        "Topic :: Text Editors :: Integrated Development Environments (IDE)",
        "Topic :: Text Processing :: Markup",
    ],
    keywords="penguin brian may resume",
)
