version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout # check out the code in the project directory

      - run:
          name: Install Spell Checker
          command: |
            sudo apt-get install aspell aspell-en

      - run:
          name: Run Spell Checker
          command: |
            ./check_spelling

  deploy-prod:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build
          command: |
            docker pull "brianmay/resume:latest"
            docker build \
              --cache-from "brianmay/resume:latest" \
              --file "Dockerfile" \
              --tag "brianmay/resume:latest" \
              --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
              --build-arg "VCS_REF=$CIRCLE_SHA1" \
              .
      - run:
          name: Docker upload
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push "brianmay/resume:latest"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          context: Docker
          requires:
            - build
          filters:
            branches:
              only: master
