name: Build and Deploy to Docker Hub

on: [push, pull_request]

jobs:
  test:
    name: Test valid HTML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Spell Checker
      run: |-
        sudo apt-get install aspell aspell-en

    - name: Run Spell Checker
      run: |-
        ./check_spelling
